#ifndef ENUM_EVENT_KEY_HPP
#define ENUM_EVENT_KEY_HPP

enum class EventKey : int {
    RIGHT_CLICK = 0,
    PAUSE_SCREEN,
    RETURN_SCREEN,
    DIARY_SCREEN,
    SWITCH_SCENE,
    DIALOGUE_SCREEN,
    STORY_SCREEN,
    OBJECTIVE_SCREEN,
    OBJECTIVE_BUTTON,
    ITEM_PICKUP,
};

#endif

